# A minimal Docker image based on Alpine Linux with a complete package index and only 5 MB in size!
FROM alpine
FROM golang:alpine

RUN apk add --no-cache git mercurial
RUN export PATH=$PATH:/usr/local/go/bin

RUN go get github.com/julienschmidt/httprouter && go get github.com/patrickmn/go-cache

# expose port
EXPOSE 80

# Add executable into image
ADD build/app /

CMD ["/app"]

# execute command when docker launches / run
#CMD ["./app"]